name: Cleanup Workflow Runs

on:
  workflow_dispatch:
    days:
      description: 'Number of days to retain'
      default: 1
    runs:
      description: 'Number of runs to retain'
      default: 0
    schedule:
      - cron: '0 0 1 * *' # Run monthly on the first of every month

jobs:
  del_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.runs }}

